### PR TITLE
[Feature] Adding pre and post step to BaseScenario

### PR DESCRIPTION
**Pull request by Zartris**
fixes https://github.com/proroklab/VectorizedMultiAgentSimulator/issues/110

### CODE REVIEW

**Comment by Zartris** [comment]
Should maybe remove the returns however the flake8 was not happy about empty methods.

**Comment by matteobettini** [comment]
Looks good! 

Can we simplify the docstring of poststep? I don’t think we need to go into cat and unsqueeze, just appending to a list is fine

**Comment by matteobettini** [comment]
Also maybe an underscore in the name like `post_step`

**Comment by Zartris** [comment]
Done

**Comment by matteobettini** [comment]
Fabulous, last addition I missed: can you add them to the BaseScenarion docstring under the optional methods?

**Comment by Zartris** [comment]
Like this?

**Comment by matteobettini** [comment]
Yeah just remove the added line

**Pull request merged**
